# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:12.13
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo # add time zone
      CACHE_VERSION: 1.16

commands:
  restore_built:
    description: "Restore the build result from cache"
    steps:
      - restore_cache:
          key: v{{ .Environment.CACHE_VERSION }}-built-cli-{{ .Revision }}
      - restore_cache:
          key: v{{ .Environment.CACHE_VERSION }}-built-json-storage-{{ .Revision }}
      - restore_cache:
          key: v{{ .Environment.CACHE_VERSION }}-built-lemon-sour-{{ .Revision }}
  restore_dependency:
    description: "Restore the dependencies result from cache"
    steps:
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package.json checksum
            # when this file is changed, this key will fail
            - v{{ .Environment.CACHE_VERSION }}-dependencies-root-{{ checksum "package.json" }}
            # Find the most recent cache used from any branch
            - v{{ .Environment.CACHE_VERSION }}-dependencies-root-
      - restore_cache:
          keys:
            - v{{ .Environment.CACHE_VERSION }}-dependencies-cli-{{ checksum "packages/cli/package.json" }}
            - v{{ .Environment.CACHE_VERSION }}-dependencies-cli-
      - restore_cache:
          keys:
            - v{{ .Environment.CACHE_VERSION }}-dependencies-json-storage-{{ checksum "packages/json-storage/package.json" }}
            - v{{ .Environment.CACHE_VERSION }}-dependencies-json-storage-
      - restore_cache:
          keys:
            - v{{ .Environment.CACHE_VERSION }}-dependencies-lemon-sour-{{ checksum "packages/lemon-sour/package.json" }}
            - v{{ .Environment.CACHE_VERSION }}-dependencies-lemon-sour-

jobs:
  install_dependency:
    executor: node
    steps:
      # Checkout repository
      - checkout

      - run:
          name: Nodejs Version
          command: node --version

      # Restore cache
      - restore_dependency

      # Install dependencies
      - run:
          name: Installing the root dependencies
          command: yarn install
      - run:
          name: Installing the sub project dependencies
          command: npx lerna bootstrap

      # Evacuation of the package.json
      - run:
          name: Evacuation of the root package.json
          command: cp ./package.json ./package.copy.json
      - run:
          name: Evacuation of the cli package.json
          command: cp ./packages/cli/package.json ./packages/cli/package.copy.json
      - run:
          name: Evacuation of the json-storage package.json
          command: cp ./packages/json-storage/package.json ./packages/json-storage/package.copy.json
      - run:
          name: Evacuation of the lemon-sour package.json
          command: cp ./packages/lemon-sour/package.json ./packages/lemon-sour/package.copy.json

      # Save cache
      - save_cache:
          paths:
            - ./node_modules/
          key: v{{ .Environment.CACHE_VERSION }}-dependencies-root-{{ checksum "package.copy.json" }}
      - save_cache:
          paths:
            - ./packages/cli/node_modules/
          key: v{{ .Environment.CACHE_VERSION }}-dependencies-cli-{{ checksum "packages/cli/package.copy.json" }}
      - save_cache:
          paths:
            - ./packages/json-storage/node_modules/
          key: v{{ .Environment.CACHE_VERSION }}-dependencies-json-storage-{{ checksum "packages/json-storage/package.copy.json" }}
      - save_cache:
          paths:
            - ./packages/lemon-sour/node_modules/
          key: v{{ .Environment.CACHE_VERSION }}-dependencies-lemon-sour-{{ checksum "packages/lemon-sour/package.copy.json" }}

  build:
    executor: node
    steps:
      - checkout

      - restore_dependency

      - run:
          name: Build
          command: npx lerna run build

      - save_cache:
          paths:
            - ./packages/cli/lib/
          key: built-cli-{{ .Revision }}
      - save_cache:
          paths:
            - ./packages/json-storage/lib/
          key: built-json-storage-{{ .Revision }}
      - save_cache:
          paths:
            - ./packages/lemon-sour/lib/
          key: built-lemon-sour-{{ .Revision }}

  test:
    executor: node
    steps:
      - checkout

      - restore_dependency

      - restore_built

      - run:
          name: Test
          command: npx lerna run test:coverage

      - run:
          name: Send coverage of test to codecov
          command: npx codecov

workflows:
  main:
    jobs:
      - install_dependency
      - build:
          requires:
            - install_dependency
      - test:
          requires:
            - build
